# Generated by Django 3.2.6 on 2021-08-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryid', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('posted', models.DateTimeField(db_index=True)),
                ('body', models.TextField()),
                ('notify', models.BooleanField()),
            ],
        ),
    ]
