# Generated by Django 2.2.2 on 2020-01-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200121_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='sidebar',
        ),
    ]
