# Generated by Django 2.2.2 on 2020-01-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_tag_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='related',
            field=models.ManyToManyField(related_name='_tag_related_+', to='pages.Tag'),
        ),
    ]
