# Generated by Django 2.2.2 on 2021-02-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='image_alt',
            field=models.TextField(null=True),
        ),
    ]
