# Generated by Django 3.2.17 on 2023-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210213_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='evergreen',
            field=models.BooleanField(default=False),
        ),
    ]
