# Generated by Django 4.2.7 on 2023-11-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_entry_evergreen"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="classic",
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="related",
            field=models.ManyToManyField(to="pages.tag"),
        ),
    ]
